In [1]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import preprocessing
import seaborn as sns
%matplotlib inline
plt.style.use('ggplot')

In [5]:
# Creating DataFrame df from CSV StandDF
df = pd.read_csv('ReadyDF1', index_col=0)

## Separate target variables from Data Frame 
## Using .ravel() to create a contiguous flattened array to change the shape of (n_samples)

####ERROR for.len()---vector y was passed when a 1d array was expected. 
####Please change the shape of y to (n_samples, ), for example using ravel().
  ##y = column_or_1d(y, warn=True)
    
y1 =df.loc[:, ['Y1']].values.ravel()
y2 =df.loc[:, ['Y2']].values.ravel()

## Drop target variables from Data Frame 
df = df.drop(['Y1','Y2'], axis=1)

## Drop C6' from DF1 
df1 = df.drop(["C6'"], axis=1)

# Displaying first five results 
df.head()

,C1,C2,C4,C7,C3',C5',C6',T4',T3',T5',S1',S2',S3'
0,2.086360,1.0,0.029074,1.710498,1,1.351792,1.306758,0.640426,0.979660,-1.241958,0.172661,-2.012621,-1.937792
1,2.413300,0.0,-0.013352,1.413903,0,2.487306,0.000000,0.644753,1.275142,-1.031589,0.180641,-1.696991,-1.706058
2,1.954243,1.0,0.020715,0.867939,0,1.214656,0.000000,0.636816,0.630286,-1.568923,0.171728,-2.562293,-2.302656
3,2.320146,1.0,0.020023,0.930745,0,1.193831,0.000000,0.539634,0.792975,-1.374089,0.187973,-2.309955,-2.039414
4,1.903090,1.0,-0.034895,2.800922,1,1.315407,1.195813,0.587413,1.045896,-1.223474,0.177183,-1.907621,-1.858090

In [6]:
df1.head()

,C1,C2,C4,C7,C3',C5',T4',T3',T5',S1',S2',S3'
0,2.086360,1.0,0.029074,1.710498,1,1.351792,0.640426,0.979660,-1.241958,0.172661,-2.012621,-1.937792
1,2.413300,0.0,-0.013352,1.413903,0,2.487306,0.644753,1.275142,-1.031589,0.180641,-1.696991,-1.706058
2,1.954243,1.0,0.020715,0.867939,0,1.214656,0.636816,0.630286,-1.568923,0.171728,-2.562293,-2.302656
3,2.320146,1.0,0.020023,0.930745,0,1.193831,0.539634,0.792975,-1.374089,0.187973,-2.309955,-2.039414
4,1.903090,1.0,-0.034895,2.800922,1,1.315407,0.587413,1.045896,-1.223474,0.177183,-1.907621,-1.858090

In [7]:
###extra trees classifier to report feature importance, 

#The idea is whatever features passing the threshold would be selected

# Feature Importance
from sklearn import datasets
from sklearn import metrics
from sklearn.ensemble import ExtraTreesClassifier

# fit an Extra Trees model to the data; Target Variable 

model = ExtraTreesClassifier()
model.fit(df1, y1)
# display the relative importance of each attribute
fi_dict = dict(zip(df1.columns, model.feature_importances_))
sorted_dict = sorted(fi_dict.items(), key=lambda kv: kv[1])
sorted_dict

[('C2', 0.015408190500578548),
 ("C3'", 0.026012908421422),
 ("S3'", 0.08825813970484833),
 ("S1'", 0.09100330156531677),
 ("T4'", 0.09281967986957111),
 ("T3'", 0.09320910244152472),
 ('C1', 0.09506325032699418),
 ("T5'", 0.09579755671417575),
 ("C5'", 0.09828621938991332),
 ("S2'", 0.10013560557452972),
 ('C4', 0.1004228916312078),
 ('C7', 0.10358315385991776)]

In [10]:
###extra trees classifier to report feature importance, 

#The idea is whatever features passing the threshold would be selected

# Feature Importance
from sklearn import datasets
from sklearn import metrics
from sklearn.ensemble import ExtraTreesClassifier

# fit an Extra Trees model to the data; Target Variable 

model = ExtraTreesClassifier()
model.fit(df, y2)
# display the relative importance of each attribute
fi_dict = dict(zip(df.columns, model.feature_importances_))
sorted_dict = sorted(fi_dict.items(), key=lambda kv: kv[1])
sorted_dict

[('C2', 0.018334657714814913),
 ("C3'", 0.03266117616812847),
 ("C6'", 0.07675663083997553),
 ("S3'", 0.07793810260507869),
 ("T4'", 0.07947315628793897),
 ("S1'", 0.07970497171322413),
 ("T5'", 0.08493235065695519),
 ('C7', 0.0866263546902338),
 ("T3'", 0.088003032588542),
 ("S2'", 0.08805085134291114),
 ('C4', 0.09352132293333179),
 ('C1', 0.09602465690923),
 ("C5'", 0.09797273554963536)]