In [11]:
# Adding Ratio Values AFTER Z-Score Normalization

In [12]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import preprocessing
%matplotlib inline
plt.style.use('ggplot')

In [13]:
# Creating DataFrame df from CSV StandDF
df = pd.read_csv('StandDF', index_col=0)

# Displaying first five results 
df.head()

,I1,I2,I3,P_IPO,P_H,P_L,P_1DAY,C1,C2,C3,...,T3,T4,T5,S1,S2,S3,C3',C5',P(mid),C6'
0,AATI,ADVANCED ANALOGIC TECHNOLOGIES INC,3674,-0.657417,-1.536646,-1.353286,-0.448017,0.061864,0.397360,1.341329,...,0.167675,0.189744,0.312555,0.016990,0.295829,0.130419,0.942972,0.073941,-0.888512,1.286365
1,ABPI,ACCENTIA BIOPHARMACEUTICALS INC,2834,-1.248445,-1.369829,-1.557354,-1.192796,1.363203,-2.516611,-0.868273,...,1.823140,1.855214,1.541652,0.305474,1.677794,1.496631,-1.060477,2.663906,-0.888512,-0.769239
2,ACAD,ACADIA PHARMACEUTICALS INC,2834,-1.602123,-0.201891,-0.192519,-1.306401,-0.464011,0.397360,-0.785803,...,-1.789733,-1.730874,-1.597768,-0.016751,-2.110875,-2.020675,-1.060477,-0.238850,-0.241240,-0.769239
3,ACHN,ACHILLION PHARMACEUTICALS INC,2834,-0.287236,0.299161,0.326368,-0.380307,0.992418,0.397360,-0.699081,...,-0.878252,-1.097495,-0.459433,0.570501,-1.006028,-0.468705,-1.060477,-0.286349,0.082395,-0.769239
4,ACLI,AMERICAN COMMERCIAL LINES INC.,4492,1.307714,1.391162,1.354312,2.359522,-0.667616,0.397360,0.438584,...,0.538766,0.501895,0.420545,0.180462,0.755567,0.600309,0.942972,-0.009048,0.891485,1.111842

In [14]:
# Using Imputed Data, creating 6 new columns 
# These columns will replace the numerical values of T1-T5 and S1-S3 with ratios 

# Number of Long Sentences / Number of Long Sentences = T4' 
df["T4'"]=df['T4']/df['T1']

# Number of Read Words / Number of Words = T3' 
df["T3'"]=df['T3']/df['T2']

# Number of Long Words / Number of Words = T5'
df["T5'"]=df['T5']/df['T2']

# Number of Positive Words / Number of Words = S1'
df["S1'"]=df['S1']/df['T2']

# Number of Negative Words / Number of Words = S2'
df["S2'"]=df['S2']/df['T2']

# Number of Uncertain Words / Number of Words = S3'
df["S3'"]=df['S3']/df['T2']

# Checking that the new attributes are in the norm_df DataFrame
df.head()

,I1,I2,I3,P_IPO,P_H,P_L,P_1DAY,C1,C2,C3,...,C3',C5',P(mid),C6',T4',T3',T5',S1',S2',S3'
0,AATI,ADVANCED ANALOGIC TECHNOLOGIES INC,3674,-0.657417,-1.536646,-1.353286,-0.448017,0.061864,0.397360,1.341329,...,0.942972,0.073941,-0.888512,1.286365,1.015002,1.385100,2.581901,0.140345,2.443739,1.077346
1,ABPI,ACCENTIA BIOPHARMACEUTICALS INC,2834,-1.248445,-1.369829,-1.557354,-1.192796,1.363203,-2.516611,-0.868273,...,-1.060477,2.663906,-0.888512,-0.769239,0.979116,1.016612,0.859650,0.170337,0.935565,0.834546
2,ACAD,ACADIA PHARMACEUTICALS INC,2834,-1.602123,-0.201891,-0.192519,-1.306401,-0.464011,0.397360,-0.785803,...,-1.060477,-0.238850,-0.241240,-0.769239,0.850319,0.988674,0.882630,0.009253,1.166078,1.116250
3,ACHN,ACHILLION PHARMACEUTICALS INC,2834,-0.287236,0.299161,0.326368,-0.380307,0.992418,0.397360,-0.699081,...,-1.060477,-0.286349,0.082395,-0.769239,1.319898,0.944333,0.494001,-0.613426,1.081723,0.503971
4,ACLI,AMERICAN COMMERCIAL LINES INC.,4492,1.307714,1.391162,1.354312,2.359522,-0.667616,0.397360,0.438584,...,0.942972,-0.009048,0.891485,1.111842,0.629924,0.974235,0.760461,0.326324,1.366272,1.085523

In [15]:
df = df.drop(['T1','T2','T3','T4','T5','S1','S2', 'P(mid)'], axis=1)

In [16]:
df.mean()

I3        4.871669e+03
P_IPO     2.126028e-16
P_H      -6.255993e-16
P_L      -2.504513e-16
P_1DAY   -1.980820e-15
C1       -1.507429e-16
C2       -8.953411e-17
C3       -6.104599e-17
C4        4.558100e-18
C5        4.607263e-15
C6        8.955691e-15
C7        9.116201e-18
S3       -1.359291e-16
C3'       2.086959e-16
C5'       7.040637e-17
C6'      -1.595335e-17
T4'       1.818446e+00
T3'       7.827608e-01
T5'      -2.759641e-01
S1'       1.711422e+00
S2'      -1.949570e+00
S3'       5.318405e-01
dtype: float64

In [17]:
# checking for null values 
print(df.isnull().sum(axis=0).tolist())

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

In [18]:
# Exporting DataFrame as CSV named StandDF
df.to_csv('Comp1', ',')