In [1]:
##This is from last  year example in week1 agenda (Work in progress)****
### there's a lot wrong with this one 

import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import preprocessing
import seaborn as sns
%matplotlib inline
plt.style.use('ggplot')

In [2]:
# Creating DataFrame df from CSV StandDF
df = pd.read_csv('CompDF1', index_col=0)


target = pd.read_csv('Targets', index_col=0)
df = pd.concat([target, df], axis=1, join_axes=[df.index])



# Displaying first five results 
df.head()

,I1,I2,I3,P_IPO,P_H,P_L,P_1DAY,Y1,Y2,C1,...,C7,C3',C5',C6',T4',T3',T5',S1',S2',S3'
0,AATI,ADVANCED ANALOGIC TECHNOLOGIES INC,3674.0,10.0,9.5,8.5,11.870000,0,1,2.086360,...,1.710498,1,1.351792,1.306758,0.640426,0.979660,-1.241958,0.172661,-2.012621,-1.937792
1,ABPI,ACCENTIA BIOPHARMACEUTICALS INC,2834.0,8.0,10.0,8.0,7.250000,1,0,2.413300,...,1.413903,0,2.487306,0.000000,0.644753,1.275142,-1.031589,0.180641,-1.696991,-1.706058
2,ACAD,ACADIA PHARMACEUTICALS INC,2834.0,7.0,14.0,12.0,6.700000,1,0,1.954243,...,0.867939,0,1.214656,0.000000,0.636816,0.630286,-1.568923,0.171728,-2.562293,-2.302656
3,ACHN,ACHILLION PHARMACEUTICALS INC,2834.0,11.5,16.0,14.0,12.390000,1,1,2.320146,...,0.930745,0,1.193831,0.000000,0.539634,0.792975,-1.374089,0.187973,-2.309955,-2.039414
4,ACLI,AMERICAN COMMERCIAL LINES INC.,4492.0,21.0,21.0,19.0,56.599998,0,1,1.903090,...,2.800922,1,1.315407,1.195813,0.587413,1.045896,-1.223474,0.177183,-1.907621,-1.858090

In [3]:
new_dataset = df.loc[:, ['I3','P_IPO', 'P_H', 'P_1DAY', 'Y1', 'Y2', 'C1', 'C7']]
new_dataset.head()

       I3  P_IPO   P_H     P_1DAY  Y1  Y2        C1        C7
0  3674.0   10.0   9.5  11.870000   0   1  2.086360  1.710498
1  2834.0    8.0  10.0   7.250000   1   0  2.413300  1.413903
2  2834.0    7.0  14.0   6.700000   1   0  1.954243  0.867939
3  2834.0   11.5  16.0  12.390000   1   1  2.320146  0.930745
4  4492.0   21.0  21.0  56.599998   0   1  1.903090  2.800922

In [4]:
# Recursive Feature Elimination
from sklearn import datasets
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression

In [5]:
#Based off of Project example from week 1 
# Importing packages for linear regression
from sklearn.feature_selection import RFE
from sklearn import linear_model

from sklearn.metrics import mean_squared_error, r2_score
from sklearn.feature_selection import RFE

# creating a copy of the data set
testtrain=pd.DataFrame.copy(df)

# Pulling our target variable into its own dataframe
y=pd.DataFrame.copy(df['Y1'])

In [6]:
# imporing packages
from sklearn import linear_model
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.model_selection import train_test_split


# creating linear regression object  
regr = linear_model.LinearRegression()

X=pd.DataFrame.copy(new_dataset)
# splitting the data into testing and training
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.5)   
# Train the model using the training sets

# fitting our model to the data
regr.fit(X_train, y_train)

# Make predictions using the testing set
y_pred = regr.predict(X_test)

# The coefficients
print('Coefficients: \n', regr.coef_)
# The mean squared error
print("Mean squared error: %.2f"
      % np.sqrt(mean_squared_error(y_test, y_pred)))
# Explained variance score: 1 is perfect prediction
print('Variance score: %.2f' % r2_score(y_test, y_pred))

Coefficients:
 [-5.99004602e-19 -4.47424790e-16  5.38467150e-16 -1.45882150e-17
  1.00000000e+00  4.50333277e-15 -4.02346895e-16  1.37335231e-16]
Mean squared error: 0.00
Variance score: 1.00

In [7]:
from sklearn.feature_selection import RFE
# imporing packages
from sklearn import linear_model
from sklearn.metrics import mean_squared_error, r2_score
# load data

# arbitrarily decide to keep 85 variables
rfe = RFE(regr, 100)
rfe.fit(new_dataset, y)
#print("Num Features: %d") % fit.n_features_
# print("Selected Features: {}".format(fit.n_features_))
# print("Selected Features: {}".format(fit.support_))
# print("Selected Features: {}".format(fit.ranking_))





X_train, X_test, y_train, y_test = train_test_split(new_dataset, y, test_size=0.3)  




# Make predictions using the testing set
y_pred = rfe.predict(X_test)

# The coefficients

# The mean squared error
print("Mean squared error: %.5f"
      % np.sqrt(mean_squared_error(y_test, y_pred)))
# Explained variance score: 1 is perfect prediction
print('Variance score: %.5f' % r2_score(y_test, y_pred))

Mean squared error: 0.00000
Variance score: 1.00000

In [ ]:

###Can't figure out why Variance score is 1.00 and that theres no M^2 error?????
###To Be Continued

In [36]:
##75% for training and 25% for testing
train_data = df[:int(len(df) * .75)] 
test_data = df[int(len(df) * .75)::int(len(df) * .25) - 1]