In [1]:
#Descriptive Statistics

In [2]:
import numpy as np 
import pandas as pd

In [3]:
#Importing Excel file, calling the DataFrame comp_df
comp_df = pd.read_excel("Competition1_raw_data.xlsx")
comp_df.head(15)

,I1,I2,I3,P(IPO),P(H),P(L),P(1Day),C1,C2,C3,...,C6,C7,T1,T2,T3,T4,T5,S1,S2,S3
0,AATI,ADVANCED ANALOGIC TECHNOLOGIES INC,3674,10,9.5,8.5,11.87,122,1,3.43,...,10600000,51.345,470,12719,11560,301,690,62,117,139
1,ABPI,ACCENTIA BIOPHARMACEUTICALS INC,2834,8,10,8,7.25,259,0,-1.62,...,2400000,25.936,791,21792,19585,510,1120,71,242,237
2,ACAD,ACADIA PHARMACEUTICALS INC,2834,7,14,12,6.7,90,1,-1.24,...,5000000,7.378,201,5262,4785,128,325,61,33,60
3,ACHN,ACHILLION PHARMACEUTICALS INC,2834,11.5,16,14,12.39,209,1,-0.91,...,4500000,8.526,328,8259,7574,177,509,80,59,110
4,ACLI,AMERICAN COMMERCIAL LINES INC.,4492,21,21,19,56.6,80,1,0.07,...,8250000,632.298,572,14830,13176,336,720,67,149,167
5,ACOM,Ancestry.com Inc.,7379,13.5,14.5,12.5,14.2,94,1,0.06,...,7407407,197.591,510,17999,13934,328,815,62,96,181
6,ACOR,ACORDA THERAPEUTICS INC,2836,6,13,11,6.72,128,1,-1.87,...,5500000,5.146,495,15758,13953,379,698,82,106,135
7,ACRX,ACELRX PHARMACEUTICALS INC,2834,5,14,12,4.55,91,0,-0.74,...,8000000,-,334,11226,10056,276,-1,55,120,122
8,ACTV,ACTIVE NETWORK INC,7372,15,18,16,15.9,100,1,-0.51,...,11000000,279.6,620,14813,13463,335,917,58,124,234
9,ACW,ACCURIDE CORP,3714,9,19,17,0,106,1,1.49,...,11000000,494.008,385,9134,8107,198,459,81,90,147
10,ADKU,"ADCARE HEALTH SYSTEMS, INC",-,-,-,-,-,-,-,-,...,-,-,332,7534,6747,169,263,51,65,74
11,ADLS,"Advanced Life Sciences Holdings, Inc.",2854,5,9,8,6,99,1,-398.1,...,7000000,0.32,253,5788,5200,138,385,29,41,70
12,ADZA,ADEZA BIOMEDICAL CORP,2835,16,16,14,19.7,126,1,0.27,...,3750000,26.499,206,5732,4963,141,259,21,43,80
13,AFFY,AFFYMAX INC,2834,25,24,22,33.88,140,1,-2.19,...,3700000,0.074,416,10562,9835,231,726,81,118,138
14,AGAM,"AGA Medical Holdings, Inc.",3845,14.5,16,15,14.6,488,1,0.18,...,13750000,166.896,624,18633,16471,380,909,98,256,172

In [4]:
#Checking out the data
comp_df.info()
#Not taking into account missing values
#682 is the total amount of rows in the Dataset as confirmed with the Excel file 
#This can be further seen looking at the tenth row

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 682 entries, 0 to 681
Data columns (total 22 columns):
I1         682 non-null object
I2         682 non-null object
I3         682 non-null object
P(IPO)     682 non-null object
P(H)       682 non-null object
P(L)       682 non-null object
P(1Day)    682 non-null object
C1         682 non-null object
C2         682 non-null object
C3         682 non-null object
C4         682 non-null object
C5         682 non-null object
C6         682 non-null object
C7         682 non-null object
T1         682 non-null object
T2         682 non-null object
T3         682 non-null object
T4         682 non-null object
T5         682 non-null object
S1         682 non-null object
S2         682 non-null object
S3         682 non-null object
dtypes: object(22)
memory usage: 117.3+ KB

In [5]:
#Having Python recognize that there are missing values in the dataset. 

#Since Python is not recognizing the "-" as missing values, we are replacing said values.
#Using np.nan as the value, the dataset recognizes that the value is Not a Number
comp_df.replace(to_replace="-", value=np.nan, inplace=True)

In [6]:
comp_df.head(15)
#Checking Row 10 now, the "-" are replaced with NaN

,I1,I2,I3,P(IPO),P(H),P(L),P(1Day),C1,C2,C3,...,C6,C7,T1,T2,T3,T4,T5,S1,S2,S3
0,AATI,ADVANCED ANALOGIC TECHNOLOGIES INC,3674,10.0,9.5,8.5,11.870000,122.0,1.0,3.43,...,10600000.0,51.345,470.0,12719.0,11560.0,301.0,690.0,62.0,117.0,139.0
1,ABPI,ACCENTIA BIOPHARMACEUTICALS INC,2834,8.0,10.0,8.0,7.250000,259.0,0.0,-1.62,...,2400000.0,25.936,791.0,21792.0,19585.0,510.0,1120.0,71.0,242.0,237.0
2,ACAD,ACADIA PHARMACEUTICALS INC,2834,7.0,14.0,12.0,6.700000,90.0,1.0,-1.24,...,5000000.0,7.378,201.0,5262.0,4785.0,128.0,325.0,61.0,33.0,60.0
3,ACHN,ACHILLION PHARMACEUTICALS INC,2834,11.5,16.0,14.0,12.390000,209.0,1.0,-0.91,...,4500000.0,8.526,328.0,8259.0,7574.0,177.0,509.0,80.0,59.0,110.0
4,ACLI,AMERICAN COMMERCIAL LINES INC.,4492,21.0,21.0,19.0,56.599998,80.0,1.0,0.07,...,8250000.0,632.298,572.0,14830.0,13176.0,336.0,720.0,67.0,149.0,167.0
5,ACOM,Ancestry.com Inc.,7379,13.5,14.5,12.5,14.200000,94.0,1.0,0.06,...,7407407.0,197.591,510.0,17999.0,13934.0,328.0,815.0,62.0,96.0,181.0
6,ACOR,ACORDA THERAPEUTICS INC,2836,6.0,13.0,11.0,6.720000,128.0,1.0,-1.87,...,5500000.0,5.146,495.0,15758.0,13953.0,379.0,698.0,82.0,106.0,135.0
7,ACRX,ACELRX PHARMACEUTICALS INC,2834,5.0,14.0,12.0,4.550000,91.0,0.0,-0.74,...,8000000.0,NaN,334.0,11226.0,10056.0,276.0,-1.0,55.0,120.0,122.0
8,ACTV,ACTIVE NETWORK INC,7372,15.0,18.0,16.0,15.900000,100.0,1.0,-0.51,...,11000000.0,279.600,620.0,14813.0,13463.0,335.0,917.0,58.0,124.0,234.0
9,ACW,ACCURIDE CORP,3714,9.0,19.0,17.0,0.000000,106.0,1.0,1.49,...,11000000.0,494.008,385.0,9134.0,8107.0,198.0,459.0,81.0,90.0,147.0
10,ADKU,"ADCARE HEALTH SYSTEMS, INC",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,332.0,7534.0,6747.0,169.0,263.0,51.0,65.0,74.0
11,ADLS,"Advanced Life Sciences Holdings, Inc.",2854,5.0,9.0,8.0,6.000000,99.0,1.0,-398.10,...,7000000.0,0.320,253.0,5788.0,5200.0,138.0,385.0,29.0,41.0,70.0
12,ADZA,ADEZA BIOMEDICAL CORP,2835,16.0,16.0,14.0,19.700001,126.0,1.0,0.27,...,3750000.0,26.499,206.0,5732.0,4963.0,141.0,259.0,21.0,43.0,80.0
13,AFFY,AFFYMAX INC,2834,25.0,24.0,22.0,33.880001,140.0,1.0,-2.19,...,3700000.0,0.074,416.0,10562.0,9835.0,231.0,726.0,81.0,118.0,138.0
14,AGAM,"AGA Medical Holdings, Inc.",3845,14.5,16.0,15.0,14.600000,488.0,1.0,0.18,...,13750000.0,166.896,624.0,18633.0,16471.0,380.0,909.0,98.0,256.0,172.0

In [7]:
#By changing the value of the "-" in the dataframe, Python was able to recognize 
#that there are missing values and the datatypes are NOT non-null objects
#But rather the first three columns are non-null objects and the rest are floats.
comp_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 682 entries, 0 to 681
Data columns (total 22 columns):
I1         682 non-null object
I2         682 non-null object
I3         674 non-null object
P(IPO)     677 non-null float64
P(H)       672 non-null float64
P(L)       672 non-null float64
P(1Day)    660 non-null float64
C1         660 non-null float64
C2         660 non-null float64
C3         646 non-null float64
C4         660 non-null float64
C5         676 non-null float64
C6         676 non-null float64
C7         610 non-null float64
T1         681 non-null float64
T2         681 non-null float64
T3         681 non-null float64
T4         681 non-null float64
T5         681 non-null float64
S1         681 non-null float64
S2         681 non-null float64
S3         681 non-null float64
dtypes: float64(19), object(3)
memory usage: 117.3+ KB

In [8]:
#Handling Missing Values

In [9]:
#Using MEDIAN of column to fill in Continuous/Float columns
#Using MODE of column to fill in Binary/Boolean columns 
comp_df['P(IPO)'].fillna(comp_df['P(IPO)'].median(), inplace=True)
comp_df['P(H)'].fillna(comp_df['P(H)'].median(), inplace=True)
comp_df['P(L)'].fillna(comp_df['P(L)'].median(), inplace=True)
comp_df['P(1Day)'].fillna(comp_df['P(1Day)'].median(), inplace=True)
comp_df['C1'].fillna(comp_df['C1'].median(), inplace=True)
comp_df['C2'].fillna(comp_df['C2'].mode(), inplace=True)
comp_df['C3'].fillna(comp_df['C3'].median(), inplace=True)
comp_df['C4'].fillna(comp_df['C4'].median(), inplace=True)
comp_df['C5'].fillna(comp_df['C5'].median(), inplace=True)
comp_df['C6'].fillna(comp_df['C6'].median(), inplace=True)
comp_df['C7'].fillna(comp_df['C7'].median(), inplace=True)
comp_df['T1'].fillna(comp_df['T1'].median(), inplace=True)
comp_df['T2'].fillna(comp_df['T2'].median(), inplace=True)
comp_df['T3'].fillna(comp_df['T3'].median(), inplace=True)
comp_df['T4'].fillna(comp_df['T4'].median(), inplace=True)
comp_df['T5'].fillna(comp_df['T5'].median(), inplace=True)
comp_df['S1'].fillna(comp_df['S1'].median(), inplace=True)
comp_df['S2'].fillna(comp_df['S2'].median(), inplace=True)
comp_df['S3'].fillna(comp_df['S3'].median(), inplace=True)
comp_df.head(15)

,I1,I2,I3,P(IPO),P(H),P(L),P(1Day),C1,C2,C3,...,C6,C7,T1,T2,T3,T4,T5,S1,S2,S3
0,AATI,ADVANCED ANALOGIC TECHNOLOGIES INC,3674,10.0,9.5,8.5,11.870000,122.0,1.0,3.43,...,10600000.0,51.345,470.0,12719.0,11560.0,301.0,690.0,62.0,117.0,139.0
1,ABPI,ACCENTIA BIOPHARMACEUTICALS INC,2834,8.0,10.0,8.0,7.250000,259.0,0.0,-1.62,...,2400000.0,25.936,791.0,21792.0,19585.0,510.0,1120.0,71.0,242.0,237.0
2,ACAD,ACADIA PHARMACEUTICALS INC,2834,7.0,14.0,12.0,6.700000,90.0,1.0,-1.24,...,5000000.0,7.378,201.0,5262.0,4785.0,128.0,325.0,61.0,33.0,60.0
3,ACHN,ACHILLION PHARMACEUTICALS INC,2834,11.5,16.0,14.0,12.390000,209.0,1.0,-0.91,...,4500000.0,8.526,328.0,8259.0,7574.0,177.0,509.0,80.0,59.0,110.0
4,ACLI,AMERICAN COMMERCIAL LINES INC.,4492,21.0,21.0,19.0,56.599998,80.0,1.0,0.07,...,8250000.0,632.298,572.0,14830.0,13176.0,336.0,720.0,67.0,149.0,167.0
5,ACOM,Ancestry.com Inc.,7379,13.5,14.5,12.5,14.200000,94.0,1.0,0.06,...,7407407.0,197.591,510.0,17999.0,13934.0,328.0,815.0,62.0,96.0,181.0
6,ACOR,ACORDA THERAPEUTICS INC,2836,6.0,13.0,11.0,6.720000,128.0,1.0,-1.87,...,5500000.0,5.146,495.0,15758.0,13953.0,379.0,698.0,82.0,106.0,135.0
7,ACRX,ACELRX PHARMACEUTICALS INC,2834,5.0,14.0,12.0,4.550000,91.0,0.0,-0.74,...,8000000.0,103.833,334.0,11226.0,10056.0,276.0,-1.0,55.0,120.0,122.0
8,ACTV,ACTIVE NETWORK INC,7372,15.0,18.0,16.0,15.900000,100.0,1.0,-0.51,...,11000000.0,279.600,620.0,14813.0,13463.0,335.0,917.0,58.0,124.0,234.0
9,ACW,ACCURIDE CORP,3714,9.0,19.0,17.0,0.000000,106.0,1.0,1.49,...,11000000.0,494.008,385.0,9134.0,8107.0,198.0,459.0,81.0,90.0,147.0
10,ADKU,"ADCARE HEALTH SYSTEMS, INC",NaN,13.5,15.0,13.0,14.845000,107.0,NaN,0.01,...,7398703.5,103.833,332.0,7534.0,6747.0,169.0,263.0,51.0,65.0,74.0
11,ADLS,"Advanced Life Sciences Holdings, Inc.",2854,5.0,9.0,8.0,6.000000,99.0,1.0,-398.10,...,7000000.0,0.320,253.0,5788.0,5200.0,138.0,385.0,29.0,41.0,70.0
12,ADZA,ADEZA BIOMEDICAL CORP,2835,16.0,16.0,14.0,19.700001,126.0,1.0,0.27,...,3750000.0,26.499,206.0,5732.0,4963.0,141.0,259.0,21.0,43.0,80.0
13,AFFY,AFFYMAX INC,2834,25.0,24.0,22.0,33.880001,140.0,1.0,-2.19,...,3700000.0,0.074,416.0,10562.0,9835.0,231.0,726.0,81.0,118.0,138.0
14,AGAM,"AGA Medical Holdings, Inc.",3845,14.5,16.0,15.0,14.600000,488.0,1.0,0.18,...,13750000.0,166.896,624.0,18633.0,16471.0,380.0,909.0,98.0,256.0,172.0

In [10]:
#Creating 5 New Columns 
comp_df["C5'"]=(comp_df['C5']/comp_df['C6'])
comp_df.head()

,I1,I2,I3,P(IPO),P(H),P(L),P(1Day),C1,C2,C3,...,C7,T1,T2,T3,T4,T5,S1,S2,S3,C5'
0,AATI,ADVANCED ANALOGIC TECHNOLOGIES INC,3674,10.0,9.5,8.5,11.870000,122.0,1.0,3.43,...,51.345,470.0,12719.0,11560.0,301.0,690.0,62.0,117.0,139.0,3.864345
1,ABPI,ACCENTIA BIOPHARMACEUTICALS INC,2834,8.0,10.0,8.0,7.250000,259.0,0.0,-1.62,...,25.936,791.0,21792.0,19585.0,510.0,1120.0,71.0,242.0,237.0,12.028832
2,ACAD,ACADIA PHARMACEUTICALS INC,2834,7.0,14.0,12.0,6.700000,90.0,1.0,-1.24,...,7.378,201.0,5262.0,4785.0,128.0,325.0,61.0,33.0,60.0,3.369134
3,ACHN,ACHILLION PHARMACEUTICALS INC,2834,11.5,16.0,14.0,12.390000,209.0,1.0,-0.91,...,8.526,328.0,8259.0,7574.0,177.0,509.0,80.0,59.0,110.0,3.299697
4,ACLI,AMERICAN COMMERCIAL LINES INC.,4492,21.0,21.0,19.0,56.599998,80.0,1.0,0.07,...,632.298,572.0,14830.0,13176.0,336.0,720.0,67.0,149.0,167.0,3.726269

In [11]:
comp_df['Y2']= np.where(comp_df['P(IPO)']<comp_df['P(1Day)'], 1, 0)
comp_df.head()
#Check in Excel

,I1,I2,I3,P(IPO),P(H),P(L),P(1Day),C1,C2,C3,...,T1,T2,T3,T4,T5,S1,S2,S3,C5',Y2
0,AATI,ADVANCED ANALOGIC TECHNOLOGIES INC,3674,10.0,9.5,8.5,11.870000,122.0,1.0,3.43,...,470.0,12719.0,11560.0,301.0,690.0,62.0,117.0,139.0,3.864345,1
1,ABPI,ACCENTIA BIOPHARMACEUTICALS INC,2834,8.0,10.0,8.0,7.250000,259.0,0.0,-1.62,...,791.0,21792.0,19585.0,510.0,1120.0,71.0,242.0,237.0,12.028832,0
2,ACAD,ACADIA PHARMACEUTICALS INC,2834,7.0,14.0,12.0,6.700000,90.0,1.0,-1.24,...,201.0,5262.0,4785.0,128.0,325.0,61.0,33.0,60.0,3.369134,0
3,ACHN,ACHILLION PHARMACEUTICALS INC,2834,11.5,16.0,14.0,12.390000,209.0,1.0,-0.91,...,328.0,8259.0,7574.0,177.0,509.0,80.0,59.0,110.0,3.299697,1
4,ACLI,AMERICAN COMMERCIAL LINES INC.,4492,21.0,21.0,19.0,56.599998,80.0,1.0,0.07,...,572.0,14830.0,13176.0,336.0,720.0,67.0,149.0,167.0,3.726269,1

In [13]:
comp_df['Y1']= np.where(comp_df['P(IPO)']<((comp_df['P(H)']+comp_df['P(L)'])/2), 1, 0)
comp_df.head()
#Check in Excel

,I1,I2,I3,P(IPO),P(H),P(L),P(1Day),C1,C2,C3,...,T2,T3,T4,T5,S1,S2,S3,C5',Y2,Y1
0,AATI,ADVANCED ANALOGIC TECHNOLOGIES INC,3674,10.0,9.5,8.5,11.870000,122.0,1.0,3.43,...,12719.0,11560.0,301.0,690.0,62.0,117.0,139.0,3.864345,1,0
1,ABPI,ACCENTIA BIOPHARMACEUTICALS INC,2834,8.0,10.0,8.0,7.250000,259.0,0.0,-1.62,...,21792.0,19585.0,510.0,1120.0,71.0,242.0,237.0,12.028832,0,1
2,ACAD,ACADIA PHARMACEUTICALS INC,2834,7.0,14.0,12.0,6.700000,90.0,1.0,-1.24,...,5262.0,4785.0,128.0,325.0,61.0,33.0,60.0,3.369134,0,1
3,ACHN,ACHILLION PHARMACEUTICALS INC,2834,11.5,16.0,14.0,12.390000,209.0,1.0,-0.91,...,8259.0,7574.0,177.0,509.0,80.0,59.0,110.0,3.299697,1,1
4,ACLI,AMERICAN COMMERCIAL LINES INC.,4492,21.0,21.0,19.0,56.599998,80.0,1.0,0.07,...,14830.0,13176.0,336.0,720.0,67.0,149.0,167.0,3.726269,1,0

In [15]:
comp_df["C3'"]=np.where(comp_df['C3']>0, 1, 0)
comp_df.head()

,I1,I2,I3,P(IPO),P(H),P(L),P(1Day),C1,C2,C3,...,T3,T4,T5,S1,S2,S3,C5',Y2,Y1,C3'
0,AATI,ADVANCED ANALOGIC TECHNOLOGIES INC,3674,10.0,9.5,8.5,11.870000,122.0,1.0,3.43,...,11560.0,301.0,690.0,62.0,117.0,139.0,3.864345,1,0,1
1,ABPI,ACCENTIA BIOPHARMACEUTICALS INC,2834,8.0,10.0,8.0,7.250000,259.0,0.0,-1.62,...,19585.0,510.0,1120.0,71.0,242.0,237.0,12.028832,0,1,0
2,ACAD,ACADIA PHARMACEUTICALS INC,2834,7.0,14.0,12.0,6.700000,90.0,1.0,-1.24,...,4785.0,128.0,325.0,61.0,33.0,60.0,3.369134,0,1,0
3,ACHN,ACHILLION PHARMACEUTICALS INC,2834,11.5,16.0,14.0,12.390000,209.0,1.0,-0.91,...,7574.0,177.0,509.0,80.0,59.0,110.0,3.299697,1,1,0
4,ACLI,AMERICAN COMMERCIAL LINES INC.,4492,21.0,21.0,19.0,56.599998,80.0,1.0,0.07,...,13176.0,336.0,720.0,67.0,149.0,167.0,3.726269,1,0,1

In [16]:
comp_df["C6'"]= np.where((comp_df['P(IPO)']>((comp_df['P(H)']+comp_df['P(L)'])/2),((comp_df['P(IPO)']-(comp_df['P(H)']+comp_df['P(L)'])/2)/(comp_df['P(H)']+comp_df['P(L)'])/2)*100%), 0)
comp_df.head()
#Check in Excel
#Clean this up

SyntaxError: invalid syntax (<ipython-input-16-0b823298b6a9>, line 1)